name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.0
          cache: npm

      - name: Copy Environment
        id: CE
        run: cp .env.example .env
        
      - name: Install Dependencies
        id: npm-ci
        run: npm ci
      
      - name: Build project
        id: build-project
        run: npm run build    
        
      - name: Test
        id: npm-ci-test
        run: npm run test